server:
  port: 8888

jasypt:
  encryptor:
    password: liky

spring:
  datasource:
    url: jdbc:mysql://39.100.149.36:3306/personal?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 409421lz
  application:
    name: test

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# 自定义jwt key
jwt:
  tokenHeader: Authorization   #JWT存储的请求头
  secret: mySecret             #JWT加解密使用的密钥
  expiration: 604800           #JWT的超期限时间(60*60*24)
  tokenHead: Liky              #JWT负载中拿到开头

